// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TollService.Infrastructure.Persistence;

#nullable disable

namespace TollService.Infrastructure.Migrations
{
    [DbContext(typeof(TollDbContext))]
    [Migration("20251120014117_Added_Number")]
    partial class Added_Number
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TollService.Domain.Road", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<LineString>("Geometry")
                        .HasColumnType("geometry(LineString,4326)");

                    b.Property<string>("HighwayType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsToll")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Ref")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<long?>("WayId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.ToTable("Roads");
                });

            modelBuilder.Entity("TollService.Domain.Toll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<double>("IPass")
                        .HasColumnType("double precision");

                    b.Property<double>("IPassOvernight")
                        .HasColumnType("double precision");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<double>("PayOnline")
                        .HasColumnType("double precision");

                    b.Property<double>("PayOnlineOvernight")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("RoadId")
                        .HasColumnType("uuid");

                    b.Property<bool>("isDynamic")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("RoadId");

                    b.ToTable("Tolls");
                });

            modelBuilder.Entity("TollService.Domain.Toll", b =>
                {
                    b.HasOne("TollService.Domain.Road", "Road")
                        .WithMany("Tolls")
                        .HasForeignKey("RoadId");

                    b.Navigation("Road");
                });

            modelBuilder.Entity("TollService.Domain.Road", b =>
                {
                    b.Navigation("Tolls");
                });
#pragma warning restore 612, 618
        }
    }
}
