// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TollService.Infrastructure.Persistence;

#nullable disable

namespace TollService.Infrastructure.Migrations
{
    [DbContext(typeof(TollDbContext))]
    [Migration("20251206010301_Add_Index_To_FromId_ToId")]
    partial class Add_Index_To_FromId_ToId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TollService.Domain.CalculatePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Cash")
                        .HasColumnType("double precision");

                    b.Property<Guid>("FromId")
                        .HasColumnType("uuid");

                    b.Property<double>("IPass")
                        .HasColumnType("double precision");

                    b.Property<double>("Online")
                        .HasColumnType("double precision");

                    b.Property<Guid>("StateCalculatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StateCalculatorId");

                    b.HasIndex("ToId");

                    b.HasIndex("FromId", "ToId");

                    b.ToTable("CalculatePrices");
                });

            modelBuilder.Entity("TollService.Domain.Road", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<LineString>("Geometry")
                        .HasColumnType("geometry(LineString,4326)");

                    b.Property<string>("HighwayType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsToll")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Ref")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<long?>("WayId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.ToTable("Roads");
                });

            modelBuilder.Entity("TollService.Domain.StateCalculator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StateCalculators");
                });

            modelBuilder.Entity("TollService.Domain.Toll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<double>("IPass")
                        .HasColumnType("double precision");

                    b.Property<double>("IPassOvernight")
                        .HasColumnType("double precision");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<int>("PaPlazaKay")
                        .HasColumnType("integer");

                    b.Property<double>("PayOnline")
                        .HasColumnType("double precision");

                    b.Property<double>("PayOnlineOvernight")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("RoadId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StateCalculatorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("isDynamic")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("RoadId");

                    b.ToTable("Tolls");
                });

            modelBuilder.Entity("TollService.Domain.TollPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int>("AxelType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CalculatePriceId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeekFrom")
                        .HasColumnType("integer");

                    b.Property<int>("DayOfWeekTo")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("TimeFrom")
                        .HasColumnType("time without time zone");

                    b.Property<int>("TimeOfDay")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("TimeTo")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("TollId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CalculatePriceId");

                    b.HasIndex("TollId");

                    b.ToTable("TollPrices", (string)null);
                });

            modelBuilder.Entity("TollService.Domain.CalculatePrice", b =>
                {
                    b.HasOne("TollService.Domain.Toll", "From")
                        .WithMany()
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TollService.Domain.StateCalculator", "StateCalculator")
                        .WithMany("CalculatePrices")
                        .HasForeignKey("StateCalculatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TollService.Domain.Toll", "To")
                        .WithMany()
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("StateCalculator");

                    b.Navigation("To");
                });

            modelBuilder.Entity("TollService.Domain.Toll", b =>
                {
                    b.HasOne("TollService.Domain.Road", "Road")
                        .WithMany("Tolls")
                        .HasForeignKey("RoadId");

                    b.Navigation("Road");
                });

            modelBuilder.Entity("TollService.Domain.TollPrice", b =>
                {
                    b.HasOne("TollService.Domain.CalculatePrice", "CalculatePrice")
                        .WithMany("TollPrices")
                        .HasForeignKey("CalculatePriceId");

                    b.HasOne("TollService.Domain.Toll", "Toll")
                        .WithMany("TollPrices")
                        .HasForeignKey("TollId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CalculatePrice");

                    b.Navigation("Toll");
                });

            modelBuilder.Entity("TollService.Domain.CalculatePrice", b =>
                {
                    b.Navigation("TollPrices");
                });

            modelBuilder.Entity("TollService.Domain.Road", b =>
                {
                    b.Navigation("Tolls");
                });

            modelBuilder.Entity("TollService.Domain.StateCalculator", b =>
                {
                    b.Navigation("CalculatePrices");
                });

            modelBuilder.Entity("TollService.Domain.Toll", b =>
                {
                    b.Navigation("TollPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
